#!/usr/bin/env node
// The lede-refusal registry: the judgment audit's verdicts, applied render-side (lib/business.mjs
// refusedLede). This guards the mechanism, not the verdicts — the registry is data, regenerated by
// re-running the audit, and its entries retire themselves when a re-extraction changes the text.
//
// What must hold:
//  1. Shape: every entry carries a non-empty lede, defect and reason, keyed by uppercase ticker.
//  2. refusedLede refuses exactly the recorded string and nothing else (self-retiring contract).
//  3. Live coupling: for every registry ticker still present in language.json with an UNCHANGED
//     lede, the hero chain must fall back — refusedLede(reg, t, current) is true by construction;
//     this asserts the wiring assumption that current === recorded implies refusal.
//  4. Decay visibility: report how many entries have retired (text changed), so a registry gone
//     mostly stale is visible in the test log long before anyone audits again.
import fs from "node:fs";
import path from "node:path";
import { refusedLede } from "../src/lib/business.mjs";

const dataDir = path.join(process.cwd(), "src", "data");
const reg = JSON.parse(fs.readFileSync(path.join(dataDir, "ledeRefusals.json"), "utf8"));
const lang = JSON.parse(fs.readFileSync(path.join(dataDir, "language.json"), "utf8")).companies || {};

let failures = 0;
const fail = (m) => { console.error(`  ✗ ${m}`); failures++; };
const ok = (m) => console.log(`  ✓ ${m}`);

const entries = Object.entries(reg.companies || {});
if (!entries.length) fail("registry is empty — the audit's verdicts are not being applied");

let shapeBad = 0;
for (const [t, r] of entries) {
  if (t !== t.toUpperCase()) { shapeBad++; continue; }
  if (!r.lede || typeof r.lede !== "string" || !r.defect || !r.reason) shapeBad++;
}
shapeBad ? fail(`${shapeBad} entries malformed (lowercase key or missing lede/defect/reason)`) : ok(`${entries.length} entries well-formed`);

// The self-retiring contract, exercised on real entries.
const [t0, r0] = entries[0];
if (!refusedLede(reg, t0, r0.lede)) fail(`refusedLede does not refuse the recorded string for ${t0}`);
if (refusedLede(reg, t0, r0.lede + " ")) fail("refusedLede matched a CHANGED string — the self-retiring contract is broken");
if (refusedLede(reg, "NO-SUCH-TICKER", r0.lede)) fail("refusedLede matched an unregistered ticker");
if (refusedLede(null, t0, r0.lede)) fail("refusedLede fired with no registry injected");
if (!failures) ok("self-retiring contract holds (exact string, exact ticker, injected data only)");

// Live decay census — informational, plus a floor: if EVERY entry has retired the registry is
// dead weight and the audit needs a re-run.
let liveN = 0, retiredN = 0, goneN = 0;
for (const [t, r] of entries) {
  const cur = lang[t]?.business;
  if (cur == null) goneN++;
  else if (cur === r.lede) liveN++;
  else retiredN++;
}
ok(`decay census: ${liveN} live, ${retiredN} self-retired (text changed), ${goneN} entry/lede gone`);
if (entries.length && liveN === 0) fail("every registry entry has retired — regenerate the registry from a fresh audit");

if (failures) { console.error(`\n❌ ledeRefusalsTest: ${failures} failure(s)`); process.exit(1); }
console.log("\n✅ ledeRefusalsTest passed");
