#!/usr/bin/env node
// The lede-audit ledger: judgment verdicts applied render-side under WITHHOLD-UNTIL-VERIFIED
// (owner-ratified 2026-08-04). A lede renders ONLY when its exact (ticker, text) pair carries
// verdict "approved" (lib/business.mjs approvedLede). This guards the mechanism, not the
// verdicts — the ledger is data, regenerated by running the audit workflows.
//
// What must hold:
//  1. Shape: every entry has a non-empty lede, a verdict in {approved, refused}, an auditedAt
//     date; refused entries carry defect + reason.
//  2. The gate contract: approvedLede passes ONLY the exact approved string — a changed string,
//     a refused entry, an unknown ticker, or a missing ledger all withhold.
//  3. Withhold-pressure census: how many stored ledes would pass the shape gates but are
//     withheld pending audit (text unaudited) — the number that says "run the audit". Reported
//     every run; failing above a generous ceiling so months of skipped audits cannot hide.
import fs from "node:fs";
import path from "node:path";
import { approvedLede, weakLede } from "../src/lib/business.mjs";

const dataDir = path.join(process.cwd(), "src", "data");
const ledger = JSON.parse(fs.readFileSync(path.join(dataDir, "ledeAudit.json"), "utf8"));
const lang = JSON.parse(fs.readFileSync(path.join(dataDir, "language.json"), "utf8")).companies || {};

let failures = 0;
const fail = (m) => { console.error(`  ✗ ${m}`); failures++; };
const ok = (m) => console.log(`  ✓ ${m}`);

const entries = Object.entries(ledger.companies || {});
if (!entries.length) fail("ledger is empty — nothing can render under withhold-until-verified");

let shapeBad = 0;
for (const [t, e] of entries) {
  if (t !== t.toUpperCase()) { shapeBad++; continue; }
  if (!e.lede || typeof e.lede !== "string" || !["approved", "refused"].includes(e.verdict) || !e.auditedAt) { shapeBad++; continue; }
  if (e.verdict === "refused" && (!e.defect || !e.reason)) shapeBad++;
}
const nApproved = entries.filter(([, e]) => e.verdict === "approved").length;
const nRefused = entries.length - nApproved;
shapeBad ? fail(`${shapeBad} entries malformed`) : ok(`${entries.length} entries well-formed (${nApproved} approved, ${nRefused} refused)`);

// The gate contract on real entries.
const appr = entries.find(([, e]) => e.verdict === "approved");
const refu = entries.find(([, e]) => e.verdict === "refused");
if (appr) {
  const [t, e] = appr;
  if (!approvedLede(ledger, t, e.lede)) fail(`approvedLede does not pass the approved string for ${t}`);
  if (approvedLede(ledger, t, e.lede + " ")) fail("approvedLede passed a CHANGED string — withhold-until-verified is broken");
  if (approvedLede(ledger, "NO-SUCH-TICKER", e.lede)) fail("approvedLede passed an unknown ticker");
  if (approvedLede(null, t, e.lede)) fail("approvedLede passed with no ledger injected — the default must be withhold");
}
if (refu) {
  const [t, e] = refu;
  if (approvedLede(ledger, t, e.lede)) fail(`approvedLede passed a REFUSED lede for ${t}`);
}
if (!failures) ok("gate contract holds: exact approved string only; changed, refused, unknown and ledgerless all withhold");

// Withhold-pressure census: shape-passing ledes with no matching audited text.
let rendering = 0, withheldRefused = 0, withheldPending = 0;
for (const [t, l] of Object.entries(lang)) {
  const s = l.business;
  if (!s || weakLede(s)) continue;
  const e = ledger.companies[t];
  if (e && e.verdict === "approved" && e.lede === s) rendering++;
  else if (e && e.verdict === "refused" && e.lede === s) withheldRefused++;
  else withheldPending++;
}
ok(`census: ${rendering} rendering, ${withheldRefused} withheld by verdict, ${withheldPending} withheld pending audit`);
// A monthly heal changes tens of ledes; hundreds pending means audits have been skipped for
// months and the site is quietly sliding to computed phrases. Loud, not locked.
const MAX_PENDING = Number(process.env.MAX_LEDES_PENDING_AUDIT || 400);
if (withheldPending > MAX_PENDING) fail(`${withheldPending} ledes withheld pending audit (> ${MAX_PENDING}) — run the audit workflow and fold in the verdicts`);
if (entries.length && rendering === 0) fail("nothing renders — the ledger no longer matches the pool at all");

if (failures) { console.error(`\n❌ ledeAuditTest: ${failures} failure(s)`); process.exit(1); }
console.log("\n✅ ledeAuditTest passed");
